require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TestRunsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # TestRun. As you add validations to TestRun, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TestRunsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all test_runs as @test_runs" do
      test_run = TestRun.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:test_runs)).to eq([test_run])
    end
  end

  describe "GET #show" do
    it "assigns the requested test_run as @test_run" do
      test_run = TestRun.create! valid_attributes
      get :show, {:id => test_run.to_param}, valid_session
      expect(assigns(:test_run)).to eq(test_run)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new TestRun" do
        expect {
          post :create, {:test_run => valid_attributes}, valid_session
        }.to change(TestRun, :count).by(1)
      end

      it "assigns a newly created test_run as @test_run" do
        post :create, {:test_run => valid_attributes}, valid_session
        expect(assigns(:test_run)).to be_a(TestRun)
        expect(assigns(:test_run)).to be_persisted
      end

      it "redirects to the created test_run" do
        post :create, {:test_run => valid_attributes}, valid_session
        expect(response).to redirect_to(TestRun.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved test_run as @test_run" do
        post :create, {:test_run => invalid_attributes}, valid_session
        expect(assigns(:test_run)).to be_a_new(TestRun)
      end

      it "re-renders the 'new' template" do
        post :create, {:test_run => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested test_run" do
      test_run = TestRun.create! valid_attributes
      expect {
        delete :destroy, {:id => test_run.to_param}, valid_session
      }.to change(TestRun, :count).by(-1)
    end

    it "redirects to the test_runs list" do
      test_run = TestRun.create! valid_attributes
      delete :destroy, {:id => test_run.to_param}, valid_session
      expect(response).to redirect_to(test_runs_url)
    end
  end

end
